Use endpoints
projecttacoma/measure-repository pull request #113
Opened 2024-10-02 17:00 UTC by lmd59

# Summary

## New behavior

## Code changes

# Testing guidance

2024-10-07 15:22 UTC, elsaperelli requested changes
Lgtm! All of my comments are just little formatting things, everything looks and works great! HUGE transition!!! 🥳

2024-10-07 19:28 UTC, lmd59 commented on app/src/server/trpc/routers/draft.ts
> +import { Bundle, OperationOutcome } from 'fhir/r4';
Mind if I do the opposite?

2024-10-07 19:31 UTC, elsaperelli commented on app/src/server/trpc/routers/draft.ts
> +import { Bundle, OperationOutcome } from 'fhir/r4';
Nope! Whatever you want :)

2024-10-07 19:32 UTC, lmd59 commented on app/src/server/trpc/routers/draft.ts
> +      const resBundle: Bundle<FhirArtifact> = await res.json();
"

2024-10-08 18:53 UTC, elsaperelli approved these changes
Lgtm!

2024-10-08 18:53 UTC, merged