Change submit to create and update
projecttacoma/measure-repository pull request #24
Opened 2023-03-22 19:03 UTC by elsaperelli

# Summary
Because of developments in a decent CRMI call, we want to move away from implementing a $submit operation on the backend and simply allow the measure repository service to support PUT/POST of a new resource (Library or Measure).

## New behavior
The measure repository service now supports PUT/POST of a new resource, where the former uses the ID provided by the requester, and the latter generates a new server ID. This functionality is implemented through `create` and `update` which are already defined in `src/types/service.ts`. This functionality is similar to that in [deqm-test-server](https://github.com/projecttacoma/deqm-test-server).

## Code changes
- `backend/README.md` - Removed $submit info, added create and update info.
- `backend/src/config/capabilityStatementResources.json` - removed submit operation.
- `backend/src/config/serverConfig.ts` - removed submit operation.
- `dbOperations.ts` - added updateResource function and changed `logger.info` to `console.log`. Is this okay? I only changed it because I was getting a winston warning with `logger.info`.
- `LibraryService.ts` / `MeasureService.ts` - added create and update functions.
- `LibraryService.test.ts` / `MeasureService.test.ts` - added unit tests for create and update.
- `utils.ts` - export `createTestResource` function.

# Testing guidance
- If you aren't sure if you have the ColorectalCancerScreeningsFHIR bundle in your database, I would reset the database:
     - `cd backend`
     - `npm run db:reset`
     - `npm run db:loadBundle "ecqm-content-r4-2021/bundles/measure/ColorectalCancerScreeningsFHIR/ColorectalCancerScreeningsFHIR-bundle.json"`
- In the root directory, run: `npm run check:all`
     - Make sure the unit tests pass.
- In the root directory, run: `npm run start:backend`
- Send some PUT and POST requests to the new endpoints in Insomnia. Attached below are some example requests you can import into Insomnia.

[update-and-create-testing.json.zip](https://github.com/projecttacoma/measure-repository/files/11043801/update-and-create-testing.json.zip)

2023-03-22 20:35 UTC, natjoe4 requested changes
Functionality looks great. Just a few inline comments. Nice work!

2023-03-22 20:35 UTC, natjoe4 commented on backend/test/services/LibraryService.test.ts
> +    });
I think this second supertest call isn't necessary here. Just ensuring that we get back a 200 response seems sufficient to me for this test.

2023-03-22 20:35 UTC, natjoe4 commented on backend/test/services/LibraryService.test.ts
> +    });
Same here, this seems like getting a bit close to integration testing. I think if we can test that the headers and status code are what we expect, we can trust mongo and asymmetrik to work as advertised in terms of actually storing the resource and making it accessible.

2023-03-22 20:35 UTC, natjoe4 commented on backend/test/services/LibraryService.test.ts
> +      );
I would put this resource creation into a `beforeAll` call in this describe block. Not sure there's anything wrong with the way you've done it here, but that's been our standard for creating test resources in the past.

2023-03-22 20:35 UTC, natjoe4 commented on backend/test/services/MeasureService.test.ts
> +      await createTestResource({ resourceType: 'Measure', id: 'exampleId', status: 'draft' }, 'Measure');
Same here re `beforeAll`

2023-03-22 20:35 UTC, natjoe4 commented on backend/test/services/LibraryService.test.ts
> +        .expect(200);
I would add a location header check here

2023-03-22 20:35 UTC, natjoe4 commented on backend/test/services/MeasureService.test.ts
> +        .expect(200);
A location header check here too

2023-03-23 15:25 UTC, natjoe4 approved these changes
Epic work

2023-03-24 15:26 UTC, mgramigna reviewed
Looks good, small comments

2023-03-24 15:26 UTC, mgramigna commented on backend/src/config/capabilityStatementResources.json
> -        {
We might want to add support for FHIR `create`/`update` to the capability statement now

2023-03-24 15:26 UTC, mgramigna commented on backend/src/services/MeasureService.ts
> +    // create new id
```suggestion
```

2023-03-24 15:37 UTC, mgramigna commented on backend/src/config/capabilityStatementResources.json
> -        {
I think they're already there? Unless I'm missing somethign

2023-03-24 15:48 UTC, mgramigna approved these changes

2023-03-24 15:48 UTC, merged