Show resources, operations, and search parameters that are part of th…
projecttacoma/measure-repository pull request #33
Opened 2023-05-08 14:18 UTC by lmd59

…e capability statement

# Summary

## New behavior

## Code changes

# Testing guidance

2023-05-08 15:03 UTC, natjoe4 requested changes
This looks great to me! Just a couple small changes. On suggestion, do we want to sort operations and search params alphabetically? We don't have many, so things are easy enough to find either way, but could be a nice touch, especially if we plan to add more search params

2023-05-08 17:36 UTC, natjoe4 approved these changes
Looks great!

2023-05-09 14:50 UTC, elsaperelli requested changes
Nice! My only suggestion is now that the resources and search parameters are alphabetized in the capability statement section, should we alphabetize the resources in the navbar so it matches? Aka Library then Measure.

2023-05-09 20:07 UTC, elsaperelli approved these changes

2023-05-10 14:33 UTC, merged