Styling/ux touchups
projecttacoma/measure-repository pull request #36
Opened 2023-05-22 19:58 UTC by mgramigna

# Summary

## New behavior

No new behavior, screenshots showcasing styling updates shown below:

**Homepage**

![image](https://github.com/projecttacoma/measure-repository/assets/16297930/1631f6b2-ad42-4be7-9048-65f4693f7487)

* Simplified all of the content. The homepage read a lot like a README to me, with instructions on running the apps and stuff which aren't super relevant if the app is already running. Users can look at the GitHub and associated docs if they want more info.
* Reduced the size of the app header and used the default primary blue color instead of the custom cyan (we can always change the colors later, I'm just keeping it default for now)
* Included search button on the homepage as the main call to action. I imagine there will be more options here as we get into the authoring functionality.

**Resource List Page**

![image](https://github.com/projecttacoma/measure-repository/assets/16297930/1dda75b5-4c5c-4ddc-bc95-106b82397ff3)

* Used contrasting background color for emphasis of the cards instead of surrounding them in a box. Used a specific pixel value for width of the paper component for the card.
* Removed back button.
* Moved search down to the center below the title and centered the title properly.

**Resource Page**

![image](https://github.com/projecttacoma/measure-repository/assets/16297930/1153b72f-c25a-44a8-ae2c-261038191356)

* Cleaned up text a bit
* Removed back button

**Misc**

Used Open Sans font for the body for now. Could change this later, but wanted to move away from the default

## Code changes

* All the above
* Removed a lot of erroneous stylings that didn't really do anything (inline styles instead of props, unnecessary margins, unnecessary CSS attributes)
* Removed back button component entirely, it's basically the same as hitting the back button in the browser, and doesn't really provide navigation to anywhere that you can't get to in 1 or 2 clicks already

# Testing guidance

Test all features

2023-05-23 13:07 UTC, elsaperelli requested changes
Great updates! I am no UI expert, but I think these changes look great and make sense to me! Just a couple inline comments and one overall suggestion...

Definitely easier said than done, but thoughts on either lining the divider in the main page up with the one in the nav bar OR making the dividers in the main pages all the same spot...right now it's all different:

<img width="713" alt="image" src="https://github.com/projecttacoma/measure-repository/assets/30158156/58d6991d-a5bd-4627-9fd7-2df5a731da1b">

<img width="713" alt="image" src="https://github.com/projecttacoma/measure-repository/assets/30158156/4b2781dc-0860-4a62-86bb-cb939aaabf47">

<img width="699" alt="image" src="https://github.com/projecttacoma/measure-repository/assets/30158156/ba5fdda0-3954-4489-8e56-cdaa53d856a5">

2023-05-23 14:20 UTC, mgramigna commented on app/src/pages/index.tsx
> +  const renderCapabilityTable = () => {
I think we can just leave it as is for now. Maybe will revisit if this makes sense to do once we have two different statuses of artifacts in the app in the first place and see how intuitive it is

2023-05-23 14:21 UTC, mgramigna commented on app/src/components/ResourceButtons.tsx
> +          </Text>
https://github.com/projecttacoma/measure-repository/pull/36/commits/365d4fa2c2cc3ec1ca315440ddc1b9e31fa22f91

2023-05-23 14:21 UTC, mgramigna commented on app/src/components/ResourceCounts.tsx
> +            padding: '24px 24px 24px 24px'
https://github.com/projecttacoma/measure-repository/pull/36/commits/365d4fa2c2cc3ec1ca315440ddc1b9e31fa22f91

2023-05-23 14:21 UTC, mgramigna commented on app/src/components/ResourceCounts.tsx
>        return (
https://github.com/projecttacoma/measure-repository/pull/36/commits/365d4fa2c2cc3ec1ca315440ddc1b9e31fa22f91

2023-05-23 14:21 UTC, mgramigna commented on app/src/pages/[resourceType]/search-result.tsx
> +          Search Results
https://github.com/projecttacoma/measure-repository/pull/36/commits/365d4fa2c2cc3ec1ca315440ddc1b9e31fa22f91 (added an indication of how many results came back)

2023-05-25 18:20 UTC, hossenlopp approved these changes
Looks much improved! Thanks for throwing in the README update too.

2023-05-25 18:35 UTC, elsaperelli approved these changes
Great updates!

2023-05-25 18:45 UTC, merged