Renders ELM for selected Library resource
projecttacoma/measure-repository pull request #39
Opened 2023-06-08 15:33 UTC by BriannaVH

# Summary 
Renders ELM for selected Library resource

## New behavior
Users can now see the rendered ELM for a selected Library resource upon clicking the ELM tab.

## Code changes
`app/src/pages/[resourceType]/[id].tsx` - I enabled the ELM tab so that users can actually click on it when it appears. I added a new Prism component in the ELM tab and make the ELM tab appear/disappear whenever appropriate.

# Testing guidance
`npm run check:all`
`npm run start:all`
Navigate to http://localhost:3001/ and select both Measure and Library packages. Check that the ELM tab appears whenever the CQL tab appears, and likewise disappears if the CQL tab isn't present. The ELM tab should not appear for any Measures. Additionally, check that the ELM tab is enabled whenever it appears on the screen and that it appropriately renders ELM whenever it is selected by the user.

2023-06-08 22:39 UTC, hossenlopp requested changes
The ELM JSON could be highlighted with a quick change. Other than that, it looks good!

2023-06-08 22:39 UTC, hossenlopp commented on app/src/pages/[resourceType]/[id].tsx
> +              <Prism language={'elm' as any} colorScheme="light">
```suggestion
              <Prism language="json" colorScheme="light">
```
The ELM is JSON and highlighting is supported in Prism so you can just use "json" for the language. Similar to how it is used for the resource JSON just above. Only difference here is that we already have the JSON as a string.

2023-06-12 19:01 UTC, mgramigna commented on app/src/pages/[resourceType]/[id].tsx
> +                {/* eslint-enable  @typescript-eslint/no-explicit-any */}
Now that we are properly using `json` as the language, we can get rid of these comments that disable the lint rules for no explicit any.

2023-06-13 19:10 UTC, mgramigna requested changes

2023-06-13 19:10 UTC, mgramigna commented on app/src/pages/[resourceType]/[id].tsx
> +  return decodedLanguage;
Suggest moving the `useMemo` part back to the component and just have this function do the extraction.

2023-06-14 13:29 UTC, mgramigna commented on app/src/pages/[resourceType]/[id].tsx
> +function Decode(link: string, jsonData: FhirArtifact) {
Last suggestion is to make this function lowercase `decode`. Uppercase/PascalCase should be reserved for react components and classes

2023-06-14 14:53 UTC, mgramigna approved these changes
Great work!

2023-06-14 18:28 UTC, hossenlopp approved these changes
This PR ended up being super clean!

2023-06-14 18:28 UTC, merged