Add versions to draft artifacts
projecttacoma/measure-repository pull request #67
Opened 2023-11-13 21:29 UTC by elsaperelli

# Summary
Part of our feedback on the [Measure Repository Service specification](https://build.fhir.org/ig/HL7/cqf-measures/measure-repository-service.html#artifact-versioning) was that the cardinality of `version` on CQFMMeasure and CQFMLibrary (derived from CQFMShareableLibrary and CQFMShareableMeasure) is 1..1. This means that we want our draft artifacts to have versions on the authoring side as well as the artifacts on the published measure repository. This PR removes the version input part of the Release Modal and increments the artifact version when it is being converted to a draft rather than deleting it.

## New behavior
- Versions of existing artifacts that are being converted to a draft are now incremented rather than deleted.
- The user can no longer specify a version when releasing a draft artifact since that draft will already have one. 
- Following the SHOULD of the measure repository specification regarding artifact versioning [here](https://build.fhir.org/ig/HL7/cqf-measures/measure-repository-service.html#artifact-versioning), we now force artifacts being uploaded to the published measure repository to follow semantic versioning and if it can't then an error will be thrown.

## Code changes
- `app/package.json`/`service/package.json`/`package-lock.json` - installed `semver` for semantic versioning
- `ReleaseModal.tsx` - removed the version user input
- `authoringFixtures.ts` - included a version of `0.0.1` on the Measure and Library skeletons
- `modifyResourceFields.ts` - increment the version of an existing artifact rather than deleting it. Added a TODO comment (feel free to remove) but I think it is something we should discuss and potentially make a task for?
- `fhir.ts` - remove `| null` for `version` property since the cardinality is 1..1.
- `dbSetup.ts`/`BaseService.ts`/`LibraryService.ts`/`MeasureService.ts` - version handling
- `README.md` - added a section about the artifact versioning handling
- `bundleUtils.ts` - added two functions: `convertToSemantic` and `handleVersionFormat`. `handleVersionFormat` converts versions that either can be coerced to semantic versioning or are of format x.x.xxx to semantic versions. 
- `LibraryService.test.ts`/`MeasureService.test.ts` - tests that the versions of artifacts uploaded to the server are properly handled
- `bundleUtils.test.ts` - tests for `handleVersionFormat`

# Testing guidance
- `npm run check:all` 

## Backend Testing
- Upload some Measures and Libraries via PUT and POST requests and ensure that their versions are properly handled. For example, upload a Measure that has a version of 1.1. Send a GET request to the location of the created artifact and the version should be 1.1.0. Do the same with versions of format x.x.xxx. Ensure that artifacts with versions that cannot be coerced to semantic versioning result in an error and do not get uploaded. 
- Test the same as above but using `npm run db:loadBundle` with a bundle that has an artifact with different versions

## Frontend Testing
- `npm run start:all`
- `localhost:3001`
- Create an artifact from scratch. Verify that the version in the JSON is `0.0.1`.
- Create an artifact from an existing artifact. Verify that the version in the JSON is incremented from the existing artifact. For example, if you have an artifact with version 3.0.0, then the draft artifact that you create from that should be 3.0.1.
- Release a draft artifact. Confirm that the version input is not there and that the released artifact has the version of the draft that it was.

2023-11-15 16:23 UTC, sarahmcdougall requested changes
Left a few comments for suggested changes, but overall infrastructure looks good 👍 Great changes here!

2023-11-15 16:31 UTC, elsaperelli commented on app/src/util/modifyResourceFields.ts
> +      console.log('hi', artifact.version);
LOL

2023-11-15 17:00 UTC, elsaperelli commented on app/src/util/modifyResourceFields.ts
> +    formattedPatch = versionParts[2].toString().padStart(3, '0');
Ikr! I was pretty pumped to find out about that

2023-11-15 19:31 UTC, elsaperelli commented on app/src/util/modifyResourceFields.ts
> +      artifact.version = inc(artifact.version, 'patch') ?? '';
I had to do some re-working of this anyways, so let me know if what I do now makes sense or if there should be any additional changes!

2023-11-15 19:52 UTC, elsaperelli commented on app/src/util/modifyResourceFields.ts
> +    artifact.version = inc(artifact.version, 'patch') ?? '';
We actually don't seem to have any documentation about the release functionality (or any authoring side functionality for that matter). Happy to do this but could also be a good EOS activity?

2023-11-16 16:19 UTC, sarahmcdougall approved these changes
Great changes here! Thanks for adding some comments surrounding the version incrementation process - I think those will be useful if we ever need to revisit this in the future. Functionality works great as well!

2023-11-17 16:39 UTC, merged