batch draft
projecttacoma/measure-repository pull request #84
Opened 2024-02-16 22:12 UTC by lmd59

# Summary

## New behavior

## Code changes

# Testing guidance

2024-03-20 19:05 UTC, elsaperelli requested changes
Woohoo batch draft!!!!

Just some small comments but overall functionality worked great for me!

2024-03-20 19:05 UTC, elsaperelli commented on app/src/server/db/dbOperations.ts
> +    console.error('Batch drafts transaction failed:' + err);
```suggestion
    console.error('Batch drafts transaction failed: ' + err);
```

2024-03-20 19:05 UTC, elsaperelli commented on app/src/server/trpc/routers/service.ts
> +      return { draftId: parentArtifact.id, children: children };
On further inspection, I don't think it actually matters

2024-03-21 13:31 UTC, lmd59 commented on app/src/server/trpc/routers/service.ts
> +      return { draftId: parentArtifact.id, children: children };
Yeah- these are sort of the children information we need on the other side, so we're good to use these instead of the childDrafts.

2024-03-21 14:42 UTC, merged